app:
  name: BixParkSampleServer
  description: Service application for bixpark
  mediaPath: H:\WorkingProjects\CeylonMobileApp\webapps\bixpark_server\_build\media
route:
  prefix: api
  version: v1
#  jdbc:postgresql://localhost:5432/bixpark_service_app_db?sslmode=disable?
db:
  host: localhost
  port: 5432
  user: postgres
  password: dewmal91
  db: bixpark_service_app_db

security:
  salt: $uyg34uiydsw3